apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-nginx
  namespace: lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-nginx
  template:
    metadata:
      labels:
        app: lab-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
